import Head from "next/head";
import Banner from "@/components/banner/banner";
import Intro from "@/components/intro/intro";
import Property from "@/components/property/property";
import WhyChoose from "@/components/whyChoose/whyChoose";
import About from "@/components/about/about";
import Service from "@/components/service/service";
import Testimonial from "@/components/testimonial/testimonial";
import Counter from "@/components/counter/counter";
import Neighborhoods from "@/components/neighborhoods/neighborhoods";
import Brands from "@/components/brands/brands";
import Blog from "@/components/blog/blog";
import Footer from "@/layout/footer/footer";
import Title from "@/components/title/title";

export default function Home() {
  return (
    <>
      <Head>
        <title>Properland - Webflow HTML website template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        agency="Real Estate Agency"
        title="Find the perfect place to Live with your family"
        image="https://assets.website-files.com/6304f6a27b2b4e7a7062ee94/6348f852232713258691f4c3_hero-main-image.png"
        description="Distinctively re-engineer revolutionary meta-services and
          premium architectures. Intrinsically incubate."
        button="Explore Property"
        key={Math.random()}
      />
      <Intro>
        <Title
          count="01"
          subTitle="Properland Intro"
          title="Buying & Selling Property In An Easy Way"
        />
      </Intro>
      <Property>
        <Title
          count="02"
          subTitle="Featured Properties"
          title="Properties for sale in your favorite area"
          className="property__text u-text-center"
        />
      </Property>
      <WhyChoose>
        <Title
          count="03"
          subTitle="Why Choose"
          title="Why Choose Our Properties Of Real Estate Industries"
          className="whyChoose__text u-text-center"
        />
      </WhyChoose>
      <About>
        <Title
          count="04"
          subTitle="About Us"
          title="42+ years of helping you find the right Propertys"
        />
      </About>
      <Service>
        <Title
          count="05"
          subTitle="Services"
          title="See How Can Help"
          className="service__text u-text-center"
        />
      </Service>
      <Testimonial />
      <Counter />
      <Neighborhoods>
        <Title
          count="06"
          subTitle="Neighborhoods"
          title="Discover The Neighborhoods"
          className="neighborhoods__text u-text-center"
        />
      </Neighborhoods>
      <Brands />
      <Blog>
        <Title
          count="07"
          subTitle="Blog"
          title="Latest Articles"
          className="u-text-center"
        />
      </Blog>
      <Footer />
    </>
  );
}
