import Head from "next/head";
import Banner from "@/components/banner";
import Intro from "@/components/intro";
import Property from "@/components/property";
import WhyChoose from "@/components/whyChoose";
import About from "@/components/about";
import Service from "@/components/service";
import Testimonial from "@/components/testimonial";
import Counter from "@/components/counter";
import Neighborhoods from "@/components/neighborhoods";
import Brands from "@/components/brands";
import Blog from "@/components/blog";
import Footer from "@/layout/footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Properland - Webflow HTML website template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        agency="Real Estate Agency"
        title="Find the perfect place to Live with your family"
        image="https://assets.website-files.com/6304f6a27b2b4e7a7062ee94/6348f852232713258691f4c3_hero-main-image.png"
        description="Distinctively re-engineer revolutionary meta-services and
          premium architectures. Intrinsically incubate."
        button="Explore Property"
        key={Math.random()}
      />
      <Intro />
      <Property />
      <WhyChoose />
      <About />
      <Service />
      <Testimonial />
      <Counter />
      <Neighborhoods />
      <Brands />
      <Blog />
      <Footer />
    </>
  );
}
